name: Deploy Workflow

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
      
jobs:

  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-workflow-main.yml

  deploy-heroku:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Heroku
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'sgcm-grupo-4'
          heroku_email: 'gerlima96@gmail.com'

          # https://itnext.io/how-to-deploy-angular-application-to-heroku-1d56e09c5147
          # https://www.devmedia.com.br/angular-cli-como-rodar-testes-e-checar-o-codigo/38248#:~:text=Assim%2C%20basta%20executar%20o%20comando,dentro%20da%20pasta%20do%20projeto.
          # https://www.focisolutions.com/2020/04/github-actions-deploying-an-angular-app/
          # https://github.com/actions/setup-node
          # https://stackoverflow.com/questions/59466378/github-actions-angular-cli
          # https://stackoverflow.com/questions/59466378/github-actions-angular-cli