name: CI Workflow Main
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_call:
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: NPM Init
        run: npm init
      - name: Install dependencies
        run: npm install
      - name: Build
        run: ng build --prod
      - name: Test
        run: ng test --watch=false --code-coverage --source-map true